name: Build SQLite3
on: [push]
jobs:
  Build-All:
    strategy:
      matrix:
        arch:
          - runner: ubuntu-latest
            target: x86_64-linux
          - runner: ubuntu-24.04-arm
            target: arm64-linux
          - runner: macos-latest
            target: x86_64-osx
          - runner: macos-latest
            target: arm64-osx
          - runner: windows-latest
            target: x86_64-win32
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Build for ${{ matrix.arch.target }}
        shell: bash
        run: ./build.sh ${{ matrix.arch.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch.target }}
          path: ./lib
  Package:
    needs: Build-All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./lib
          merge-multiple: true
      - name: Package up all architectures
        run: tar czf sqlite3-libs.tar.gz ./lib
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite3-libs.tar.gz
          path: sqlite3-libs.tar.gz
